### ISSUE TITLE
Add github pages integration and mdbook for easy publishing and viewing

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-unofficial/patterns#44] opened 2016-10-28 11:48 UTC
I've got a [personal project](https://github.com/Michael-F-Bryan/cheat-sheets) which does something pretty similar to this. It's essentially a git repository full of markdown pages. 

What I did is use something called [mdbook](https://github.com/azerupi/mdBook/) which will take all the markdown files and turn them into structured html. I then added a `travis.yml` which will rebuild the html every time I commit some work and then automatically push to the ghpages branch.

I was wondering if you wanted to do something similar to make it easier for people to read and navigate all the useful documents here. It shouldn't require much effort, you just put all the `*.md` source files in a `src` directory and write a short `SUMMARY.md` file to tell mdbook where everything goes. 

here's my `SUMMARY.md`:

```
# Summary

- [Using this Document](./using-the-wiki.md)
- [JavaScript](./JavaScript/javascript.md)
- [Docker](./docker-images.md)
- [Python](./Python/index.md)
    - [SqlAlchemy](./Python/sqlalchemy.md)
- [Basic Server Setup](./basic-server-setup.md)
- [Rust](./Rust/index.md)
    - [Using Rust outside Rust](./Rust/rust_interop.md)
    - [Emails and Templates](./Rust/emails_and_templates.md)
- [Testing In C](./testing_in_c.md)
- [LaTeX Snippets](./latex.md)
```

And the generated documents are viewable [here](https://michael-f-bryan.github.io/cheat-sheets/).

**Comment by lfairy** [comment] 2017-01-03 23:10
We should consider the original [GitBook](https://www.gitbook.com/). It has built-in GitHub integration (so no fiddling with Travis), has a slick interface, and it's open source as well. Given that we're low on manpower, I'd prefer the solution that takes the least effort to set up and maintain -- GitBook is the best in that regard.

**Comment by killercup** [comment] 2017-01-05 14:25
Dupe of #6?

**Comment by lfairy** [comment] 2017-01-05 23:09
Yep, I'd call it a dupe. Thanks for the pointer.

**Closed by lfairy** 2017-01-05 23:09 UTC
